name: Update for new release of evernote-backup

on:
  schedule:
    - cron: '0 0 * * *'
  workflow_dispatch:

permissions:
  contents: write
  pull-requests: write

jobs:
  release-check:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Get latest release tag of evernote-backup
        id: get_release
        run: |
          latest_tag=$(curl -s https://api.github.com/repos/vzhd1701/evernote-backup/releases/latest | jq -r .tag_name)
          echo "Latest tag: $latest_tag"
          echo "tag=$latest_tag" >> "$GITHUB_ENV"

      - name: Update flake file
        id: update_flake
        run: |
          latest_tag=${{ env.tag }}
          if [ -z "$latest_tag" ]; then
            echo "Error: latest_tag is empty."
            exit 1
          fi
          sed -i "s|url = \"github:vzhd1701/evernote-backup\";|url = \"github:vzhd1701/evernote-backup?ref=refs/tags/${latest_tag}\";|" flake.nix

      - name: Push changes and create PR
        uses: peter-evans/create-pull-request@v6
        with:
          branch: update-evernote-backup-${{ env.tag }}
          base: main
          title: "Update evernote-backup to ${{ env.tag }}"
          body: "This PR updates evernote-backup to version ${{ env.tag }}."
          labels: 'release-update'
